apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter-ds
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      tolerations:
      - key: "cmk"
        operator: "Exists"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ PPOD_label if version == '2.0' else 'cluster_name' }}
                operator: In
                values:
                - "{{ PPOD_name if version == '2.0' else K8s_cluster_name }}"
      hostNetwork: true
      imagePullSecrets:
      - name: nexus-docker-secret
      containers:

      - name: node-exporter
        image: {{ docker_repo }}:{{ docker_repo_port }}/prom/node-exporter:v0.15.2
        args: ["{{ disable_nodeexporter_module }}"]
        ports:
        - containerPort: 9100
          hostPort: 9100

      volumes:

      - name: dev-cpu
        hostPath:
          path: /dev/cpu

      - name: cert
        secret:
          secretName: kafka-cert
      - name: config
        configMap:
          name: kafka-conf
      - name: ssh-mount
        hostPath:
          path: /home/ubuntu/.ssh
